// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package downloaderProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DownloaderServiceClient is the client API for DownloaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DownloaderServiceClient interface {
	DownloadThumbnail(ctx context.Context, in *DownloadTRequest, opts ...grpc.CallOption) (*DownloadTResponse, error)
}

type downloaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloaderServiceClient(cc grpc.ClientConnInterface) DownloaderServiceClient {
	return &downloaderServiceClient{cc}
}

func (c *downloaderServiceClient) DownloadThumbnail(ctx context.Context, in *DownloadTRequest, opts ...grpc.CallOption) (*DownloadTResponse, error) {
	out := new(DownloadTResponse)
	err := c.cc.Invoke(ctx, "/downloaderProto.DownloaderService/DownloadThumbnail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloaderServiceServer is the server API for DownloaderService service.
// All implementations must embed UnimplementedDownloaderServiceServer
// for forward compatibility
type DownloaderServiceServer interface {
	DownloadThumbnail(context.Context, *DownloadTRequest) (*DownloadTResponse, error)
	mustEmbedUnimplementedDownloaderServiceServer()
}

// UnimplementedDownloaderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDownloaderServiceServer struct {
}

func (UnimplementedDownloaderServiceServer) DownloadThumbnail(context.Context, *DownloadTRequest) (*DownloadTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadThumbnail not implemented")
}
func (UnimplementedDownloaderServiceServer) mustEmbedUnimplementedDownloaderServiceServer() {}

// UnsafeDownloaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloaderServiceServer will
// result in compilation errors.
type UnsafeDownloaderServiceServer interface {
	mustEmbedUnimplementedDownloaderServiceServer()
}

func RegisterDownloaderServiceServer(s grpc.ServiceRegistrar, srv DownloaderServiceServer) {
	s.RegisterService(&DownloaderService_ServiceDesc, srv)
}

func _DownloaderService_DownloadThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServiceServer).DownloadThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/downloaderProto.DownloaderService/DownloadThumbnail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServiceServer).DownloadThumbnail(ctx, req.(*DownloadTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DownloaderService_ServiceDesc is the grpc.ServiceDesc for DownloaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DownloaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "downloaderProto.DownloaderService",
	HandlerType: (*DownloaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DownloadThumbnail",
			Handler:    _DownloaderService_DownloadThumbnail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "downloader.proto",
}
